---
#-------------------------------
# General Site Settings

title: Home
logo: 
author: themefisher
description: this is meta description
email: khiera.n.honore@gmail.com
phone: +215 391 3103
address: 1017 W Nedro Ave, Philadelphia, PA 19141
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hey there! I`m <br> Khiera, <br> Welcome!

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "https://twitter.com/KhonoComputes" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Front End Web Design, color: "#fdb157", value: "60%" }
  - { name: Data Analysis, color: "#9473e6", value: "20%" }
  - { name: C# and C++, color: "#bdecf6", value: "20%" }
  - { name: Copywriting, color: "#ffbcaa", value: "40%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: IT Support Technician,
      icon: "icon-1.png",
      date: "Oct 2014 - Dec 2020",
      organization: "THANKFUL LEARNING CENTER",
    }
  - {
      name: Energy Assistance Worker,
      icon: "icon-2.png",
      date: "Sep 2018 - Sep 2021",
      organization: "COMMONWEALTH OF PA",
    }
  - {
      name: Contact Representative,
      icon: "icon-3.png",
      date: "Nov 2021 - Present",
      organization: "SOCIAL SECURITY ADMINISTRATION",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Marters in UX Design,
      date: "2006",
      organization: "Masassusets Institute of Technology",
    }
#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Web Design,
      icon: ti-palette,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }
  - {
      name: Data Analytics,
      icon: ti-vector,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: true, # Add true to select section
    }
  - {
      name: Coding,
      icon: ti-panel,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }
  - {
      name: Graphic Design and Illustration,
      icon: ti-panel,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }
#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "WEB DESIGN", type: "design" }
  - { title: "DATA VISUALIZATION", type: "data" }
  - { title: "CODING", type: "coding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: khiera.n.honore@gmail.com
